### ISSUE TITLE
Funnel Query

### ISSUE THREAD

**Issue by behrad** [par6n/chabok-job-offer#2]
your funnel query is not real-world.

Funnel queries are implemented two ways using either JOINs or SUB-Selects.
please search more and write a code to implement that.

**Comment by par6n** [comment]
I'm a little confused with the scenario here.
I think I need to add another column to the schema to store the User IDs. Correct?

**Comment by behrad** [comment]
No, look at example correct queries for event funnel analysis.
You can find some hints looking at:

What is Funnel Analysis?
https://help.moengage.com/hc/en-us/articles/360019719252-Getting-Started-with-MoEngage-Funnels
https://docs.heap.io/docs/heap-connect-funnel-analysis

Sample Funnel SQL Queries:

http://www.silota.com/docs/recipes/sql-funnel-analysis.html

https://medium.com/firebase-developers/bigquery-and-google-analytics-for-firebase-lets-create-a-multi-part-funnel-420d837c1f5e

**Comment by par6n** [comment]
Both of the sample SQL queries use user_id columns.

**Comment by behrad** [comment]
Yes, but the main issue here is not the user_id, but the query semantic itself

**Comment by behrad** [comment]
After that try to use JOINS or SUB Selects to define a correct funnel query!

**Comment by par6n** [comment]
Addressed in 9c61cb06ee5144415cbc5a4be27d7a57a4581622
I think they're correct now. :thinking:
